name = "los-pumas-worker"
main = "src/index.js"
compatibility_date = "2026-07-31"

[vars]
ALLOWED_ORIGIN = "https://g041.github.io"

[[kv_namespaces]]
binding = "DB"
id = "1e68cd75f02c40d2b3ea1f83a6b9e975"
